config/routes.rb
Rails.application.routes.draw do
  
  resources :tweets
  resources :monstruos
  
  root 'tweets#default'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monstruo.rb
class Monstruo < ApplicationRecord
  has_many :tweets, dependent: :destroy

  default_scope -> { order :nombre }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :monstruo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  
  def index
    @monstruo=Monstruo.all
  end

  def show
  	#punto1
  	@monstruo=Monstruo.find(params[:id])
    #punto5
    if @monstruo.tweets.count <1 then 
      redirect_to monstruos_path, notice: 'no tiene tweets'
    end
  end

  def edit    
  end
  
  def destroy
  	#punto3
  	monstruo= Monstruo.find(params[:id])
  	monstruo.destroy
  	redirect_to monstruos_path, notice: 'se borro correctamente'
  end
end

app/controllers/tweets_controller.rb
# encoding = utf-8
class TweetsController < ApplicationController
  
  def new
  	@tweet = Tweet.new
  end

  def default    
  end
  
  def index
  end

  def show
  end

  # -----------------
  # CREATE
  # El método create recibe params = { tweet: { monstruo_id: valor, estado: valor } }
  #punto4
  def create
    tweet = Tweet.new(params.require(:tweet).permit(:monstruo_id, :estado))
    if tweet.save
      redirect_to tweets_path, notice: "tweet guardado correctamente"
    else
      flash[:error]= "hubo un error al cargarlo"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          
          
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "logo" %>
            Critter
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>

    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Critter </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container"> 
  
  <% if flash[:notice] %>
    <div class="alert alert-info"> <%= flash[:notice] %> </div>
  <% end %>
  
	<%= yield %>
</div>
<%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/monstruos/edit.html.erb
<h1> Editar monstruo </h1>

<p> No está hecho </p>

app/views/monstruos/index.html.erb
<h1> Listado de Monstruos </h1>

<table class="table table-dark table-striped">

	<tr>
		<th> Nombre </th>
		<th> Descripción </th>
		<th> Critter start </th>
		<th> Acciones </th>
	</tr>

	<% monstruos = Monstruo.all %>
	<% monstruos.each do |monstruo| %>
		<tr>
			<td> <%= link_to monstruo.nombre, monstruo %> </td>
			<td> <%= monstruo.descripcion %> </td>
			<td> <%= (monstruo.critter_star) ? 'Si' : 'No' %> </td>
			<td>
				<%= link_to "Modificacion", edit_monstruo_path(monstruo), class: 'btn btn-info btn-sm' %>
				<%= link_to "Eliminar", monstruo, method: :delete, class: 'btn btn-danger btn-sm' %>
			</td>
		</tr>
	<% end %>

	<% if monstruos.size == 0 %>
		<tr> <td colspan="3"> No hay monstruos </td> </tr>
	<% end %>

</table>

app/views/monstruos/show.html.erb
Ver un monstruo <br>
/app/views/monstruos/show.html.erb

<!-- punto2 -->
<h1> <%= @monstruo.nombre %> </h1>
<p> descripcion: <%=@mosntruo.descripcion %> </p>
<h6> tweets: </h6>
<ul>
	<% @monstruo.tweets.all.each do |tweet| %>
	<li> <%= tweet.estado %> </li>
	<%end%>
</ul>

app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

app/views/tweets/default.html.erb
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  <li> <%= link_to "Nuevo Tweet", new_tweet_path %></li>
  <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>  
</ul>

app/views/tweets/index.html.erb
<!-- Listado de tweets -->

app/views/tweets/new.html.erb
<div class="container">
	<h1> Crear un tweet para un monstruo </h1>

	<%= form_for @tweet do |f| %>
		
		<div class="row">
			<div class="col-md-6">
				<%= f.label :monstruo_id, 'Monstruo' %>
  				<%= collection_select(:tweet, :monstruo_id, Monstruo.all, :id, :nombre, {}, { class: 'form-control'}) %>
  			</div>
  		</div>


		<div class="row">
			<div class="col-md-6">
				<%= f.label :estado %>
  				<%= f.text_area :estado, class: 'form-control', label: 'Estado', placeholder: 'Ingrese el estado' %>
  			</div>
  		</div>

  		<%= f.submit "Crear tweet", class: 'btn btn-primary' %>
  	</div>
<% end %>
</div>

app/views/tweets/show.html.erb
<!-- Ver un tweet -->
Detalle del tweet